# Copyright (c) The mlkem-native project authors
# Copyright (c) The slhdsa-c project authors
# SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT

name: CBMC
permissions:
  contents: read
on:
  workflow_call:
  workflow_dispatch:

jobs:
  cbmc:
    name: CBMC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/cbmc
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
